[[colors.indexed_colors]]
color = "#F5A97F"
index = 16

[[colors.indexed_colors]]
color = "#F4DBD6"
index = 17

[colors.bright]
black = "#5B6078"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#9BEC00"
magenta = "#F5BDE6"
red = "#FF204E"
white = "#A5ADCB"
yellow = "#EED49F"

[colors.cursor]
cursor = "#F4DBD6"
text = "#24273A"

[colors.dim]
black = "#26355D"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#A91D3A"
white = "#B8C0E0"
yellow = "#EED49F"

[colors.hints.end]
background = "#4d1a9e"
foreground = "#24273A"

[colors.hints.start]
background = "#EED49F"
foreground = "#24273A"

[colors.normal]
black = "#26355D"
blue = "#8AADF4"
cyan = "#8BD5CA"
green = "#A6DA95"
magenta = "#F5BDE6"
red = "#FF204E"
white = "#B8C0E0"
yellow = "#EED49F"

[colors.primary]
background = "#212121"
bright_foreground = "#CAD3F5"
dim_foreground = "#CAD3F5"
foreground = "#CAD3F5"

[colors.search.focused_match]
background = "#A6DA95"
foreground = "#24273A"

# [colors.search.footer_bar]
# background = "#A5ADCB"
# foreground = "#24273A"

[colors.search.matches]
background = "#212121"
foreground = "#24273A"

[colors.selection]
background = "#F4DBD6"
text = "#24273A"

[colors.vi_mode_cursor]
cursor = "#B7BDF8"
text = "#24273A"
