[[colors.indexed_colors]]
color = "#E49B5D"
index = 16

[[colors.indexed_colors]]
color = "#D47766"
index = 17

[colors.bright]
black = "#867462"
blue = "#A3A9CE"
cyan = "#89B3B6"
green = "#85B695"
magenta = "#CF9BC2"
red = "#D47766"
white = "#ECE1D7"
yellow = "#EBC06D"

[colors.cursor]
cursor = "#F4DBD6"
text = "#24273A"

[colors.dim]
black = "#292522"
blue = "#273142"
cyan = "#253333"
green = "#233524"
magenta = "#422741"
red = "#7D2A2F"
white = "#403A36"
yellow = "#8B7449"

[colors.hints.end]
background = "#4d1a9e"
foreground = "#24273A"

[colors.hints.start]
background = "#EED49F"
foreground = "#24273A"

[colors.normal]
black = "#34302C"
blue = "#7F91B2"
cyan = "#7B9695"
green = "#78997A"
magenta = "#B380B0"
red = "#BD8183"
white = "#C1A78E"
yellow = "#E49B5D"

[colors.primary]
bright_foreground = "#CAD3F5"
dim_foreground = "#CAD3F5"
background = "#292522"
foreground = "#ECE1D7"

[colors.search.focused_match]
background = "#A6DA95"
foreground = "#24273A"

[colors.search.matches]
background = "#212121"
foreground = "#24273A"

[colors.selection]
background = "#F4DBD6"
text = "#24273A"

[colors.vi_mode_cursor]
cursor = "#B7BDF8"
text = "#24273A"
