# Performance tweaks
[scrolling]
  multiplier = 3  # Smoother scrolling

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "on"
shape = "block"

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
opacity = 1.0
decorations = "full"
dynamic_title = true
startup_mode = "windowed"

[window.dimensions]
columns = 110
lines = 35

[window.padding]
x = 5
y = 5


[font]
size = 8
offset = { x = 0, y = 2 }
	[font.normal]
	# family = "BigBlueTerm437 Nerd Font Mono"
	family = "GohuFont 11 Nerd Font Mono"
	style = "bold"

[general]
live_config_reload = true
import = ["/home/crypt/.config/alacritty/colors.toml"]
